version: '3.3'

networks:
  kong-net:
    name: kong-net
    driver: bridge
    external: true

services:
  registers-api:
    build: .
    container_name: registers-api
    networks:
      - kong-net
    ports:
      - 3002:3002
    volumes:
      - .:/go/src/app
    env_file:
      - .env