version: '3.3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/app
    command: go run main.go
  db:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

