version: '3.3'

networks:
  kong-net:
    name: kong-net
    driver: bridge
    external: true

services:
  app:
    build: .
    networks:
      - kong-net
    ports:
      - 3000:3000
    volumes:
      - .:/go/src/app

  mysql: 
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registers
    networks:
      - kong-net
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    networks:
      - kong-net
    ports:
      - 8080:8080
